### PR TITLE
Update rules

### PR DESCRIPTION
**Pull request by horosgrisa**
This fix error with `check-redundant-params`

### CODE REVIEW

**Comment by simonkberg** [comment]
Thanks for the PR. I'm not completely sure what all these rule changes entail, because frankly I'm not using JSDoc anymore. Would you be interested in taking over maintenance of this package? It's a completely unofficial extension to [standard](https://github.com/feross/standard).

**Comment by horosgrisa** [comment]
@simonkberg OK, it will be nice.

**Comment by simonkberg** [comment]
cool! I've added you to the npm package, but I can't transfer ownership yet since you have a fork of this repo with the same name. if you rename it or delete it and let me know I can complete the transfer

**Comment by horosgrisa** [comment]
@simonkberg ОК, I deleted the repo.

**Pull request merged**
